### ISSUE TITLE
Could not invoke MusicControlManager.setNowPlaying

### ISSUE THREAD

**Issue by vennassafir** [tanguyantoine/react-native-music-control#71] opened 2017-05-29 05:19 UTC
Hi, I'm doing a music player. When ı call a song, app crashed and this error appear. Please help me?
Thanks..

onLoad(params) {
     this.setState({toggleFull:false}); 
     SongCaught = false;
    if(FirstDispatch){
        FirstDispatch = false;
    }
    else{
        this.setState({playing:true})
    } 
    
     MusicControl.setNowPlaying({
        title: this.props.realSong.title,
        artwork: this.props.realSong.artwork_url, // URL or RN's image require()
       // color: 0x3f20b8

    })  
    MusicControl.on('play', () => {
        MusicControl.updatePlayback({
            state: MusicControl.STATE_PLAYING, // (STATE_ERROR, STATE_STOPPED, STATE_PLAYING, STATE_PAUSED, STATE_BUFFERING)
        })
        this.setState({ playing: !this.state.playing });
    })

    this.setState({ songDuration: params.duration });
    songLoaded = true;
    this.props.dispatch(onLoadTrigger(songLoaded));
    let songDataUse = this.props.realSong;

    var parsed = {
          artwork_url : songDataUse.artwork_url,
          genre:songDataUse.genre,
          duration : songDataUse.duration,
          waveform_url: songDataUse.waveform_url,
          id: songDataUse.id,
          stream_url:songDataUse.stream_url,
          title:songDataUse.title,
          tag_list:songDataUse.tag_list,
          permalink: songDataUse.permalink
       }   
      this._sendPlayingSongsFirebase(parsed);
}

2. Platform ?
   - [X] Android
   
   
3. Device
  - [X] Real device

**Comment by tanguyantoine** [comment] 2017-05-29 09:57
Can you provide error logs and/or application repository/code ?

**Comment by vennassafir** [comment] 2017-05-29 16:04
I can send app code to your email address

E/unknown:React( 6916): Exception in native call
E/unknown:React( 6916): java.lang.RuntimeException: Could not invoke MusicControlManager.setNowPlaying
E/unknown:React( 6916): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:382)
E/unknown:React( 6916): 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
E/unknown:React( 6916): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/unknown:React( 6916): 	at android.os.Handler.handleCallback(Handler.java:733)
E/unknown:React( 6916): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/unknown:React( 6916): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/unknown:React( 6916): 	at android.os.Looper.loop(Looper.java:146)
E/unknown:React( 6916): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
E/unknown:React( 6916): 	at java.lang.Thread.run(Thread.java:841)
E/unknown:React( 6916): Caused by: java.lang.reflect.InvocationTargetException
E/unknown:React( 6916): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/unknown:React( 6916): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/unknown:React( 6916): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
E/unknown:React( 6916): 	... 8 more
E/unknown:React( 6916): Caused by: java.lang.NoSuchMethodError: android.media.RemoteControlClient$MetadataEditor.putObject
E/unknown:React( 6916): 	at android.support.v4.media.session.MediaSessionCompatApi19.addNewMetadata(MediaSessionCompatApi19.java:80)
E/unknown:React( 6916): 	at android.support.v4.media.session.MediaSessionCompatApi19.setMetadata(MediaSessionCompatApi19.java:50)
E/unknown:React( 6916): 	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setMetadata(MediaSessionCompat.java:1729)
E/unknown:React( 6916): 	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setActive(MediaSessionCompat.java:1649)
E/unknown:React( 6916): 	at android.support.v4.media.session.MediaSessionCompat.setActive(MediaSessionCompat.java:408)
E/unknown:React( 6916): 	at com.tanguyantoine.react.MusicControlModule.setNowPlaying(MusicControlModule.java:236)
E/unknown:React( 6916):  
.
.
.
E/AndroidRuntime( 6916): FATAL EXCEPTION: Thread-25428
E/AndroidRuntime( 6916): Process: com.umc.ultramusicplayer, PID: 6916
E/AndroidRuntime( 6916): java.lang.NoSuchMethodError: android.media.RemoteControlClient$MetadataEditor.putObject
E/AndroidRuntime( 6916): 	at android.support.v4.media.session.MediaSessionCompatApi19.addNewMetadata(MediaSessionCompatApi19.java:80)
E/AndroidRuntime( 6916): 	at android.support.v4.media.session.MediaSessionCompatApi19.setMetadata(MediaSessionCompatApi19.java:50)
E/AndroidRuntime( 6916): 	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setMetadata(MediaSessionCompat.java:1729)
E/AndroidRuntime( 6916): 	at android.support.v4.media.session.MediaSessionCompat.setMetadata(MediaSessionCompat.java:493)
E/AndroidRuntime( 6916): 	at com.tanguyantoine.react.MusicControlModule$1.run(MusicControlModule.java:224)
E/AndroidRuntime( 6916): 	at java.lang.Thread.run(Thread.java:841)

**Comment by tanguyantoine** [comment] 2017-05-30 08:50
@vennassafir did you well follow setup instruction ? @Guichaguri any thoughts ?

**Comment by vennassafir** [comment] 2017-05-30 09:17
it is working before updated react native version.. Now react native version 44. it was working 42.

**Comment by Guichaguri** [comment] 2017-05-30 13:13
It seems to be a problem with the support library.
Which Android version are you using?
Can you try running it after executing this command: `gradle build --refresh-dependencies`?

**Comment by vennassafir** [comment] 2017-05-31 11:59
I using Android version 25. 
After which process I will run this command?

**Comment by Guichaguri** [comment] 2017-05-31 14:13
Run it before building the app.
You mean API level 25, right? Which would be Android Nougat (7.1)
That's really strange, a lollipop+ device shouldn't use `RemoteControlClient`

**Comment by vennassafir** [comment] 2017-05-31 16:48
When  I run the app  on the android api version 23, the plugin was running fine. But, when I update the application I got the errors below and couldnt get apk release build.

To solve the error below, I updated to android api 25, I got the release build but the plugin gave the errors that I got in the first place.@Guichaguri I tried your solution above, but id wouldnt work.  

Hope you can help out with this .


/Users/serkanuslu/Desktop/ultra-music-player-project_2/android/app/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
/Users/serkanuslu/Desktop/ultra-music-player-project_2/android/app/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
/Users/serkanuslu/Desktop/ultra-music-player-project_2/android/app/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/Users/serkanuslu/Desktop/ultra-music-player-project_2/android/app/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'

**Comment by Guichaguri** [comment] 2017-05-31 18:54
You have to, not only update the API version, but also update the support library version. If you don't really need to update, please, keep using API level 23, which is the one that React Native is built on and tested on.

**Comment by vennassafir** [comment] 2017-06-03 12:47
Thank you your answers,  but still plugin doesn't working on Android 4.4

Do you think to update plugin soon?

**Comment by tanguyantoine** [comment] 2017-09-17 03:34
@vennassafir we have release multiple time the public, is you issue still present ? 
@Guichaguri is Android 4.4 an old version ?

**Comment by Guichaguri** [comment] 2017-09-17 13:55
@tanguyantoine Pretty much, it was released in October, 2013 and there are still 15% of active devices running it, according to Google

@vennassafir It might be a problem with your player, not with this package. On versions below 5.0, the support library uses an older deprecated feature for lockscreen controls. That feature has a lot of requirements: audio focus, the media metadata has to be updated **after** the audio starts playing, etc. Your app has to follow all ofthem to work properly

**Comment by Guichaguri** [comment] 2017-11-03 16:03
I'll be closing this for inactivity. Feel free to reopen if the problem persists.

**Closed by Guichaguri** 2017-11-03 16:03 UTC
Labels: Android

**Comment by kesha-antonov** [comment] 2017-12-01 06:41
I do have this problem
Not sure what's the cause

**Comment by abrown1982** [comment] 2018-01-10 20:51
There is a bug I found in this, only happens on Android 4.4 when using this plugin.  Is resolved by changing MusicControlModule.java line 231 to not send the rating in the metadata if using an Android API less than 19.  So changing from:

`md.putRating(MediaMetadataCompat.METADATA_KEY_RATING, rating);`
to
`if (android.os.Build.VERSION.SDK_INT > 19) {
    md.putRating(MediaMetadataCompat.METADATA_KEY_RATING, rating);
}`

Will submit a pull request if I get a chance.

**Comment by kesha-antonov** [comment] 2018-01-11 07:53
@abrown1982 Hello! Nice. Please submit PR
