### ISSUE TITLE
(Android 9 / Samsung S9) Unable to create service com.tanguyantoine.react.MusicControlNotification$NotificationService:

### ISSUE THREAD

**Issue by jamsch** [tanguyantoine/react-native-music-control#244] opened 2019-03-18 21:37 UTC
# Description

App crashes with the following devices in a production app:

- SM-G960U
- SM-G960F
- SM-G960W

All devices listed above are running Android 9

2. Platform ?
    - [ ] iOS
    - [x] Android
  
3. Device
    - [ ] Simulator
    - [x] Real device

## Stack trace

![Selection_029](https://user-images.githubusercontent.com/12927717/54565340-d9898780-4a32-11e9-900d-6a3f0ca410cb.png)

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Notification com.tanguyantoine.react.MusicControlNotification.a(android.support.v4.app.y$c, boolean)' on a null object reference
    at com.tanguyantoine.react.MusicControlNotification$NotificationService.onCreate
    at android.app.ActivityThread.handleCreateService(ActivityThread.java:3728)
    at android.app.ActivityThread.access$1400(ActivityThread.java:235)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:6981)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
java.lang.RuntimeException: Unable to create service com.tanguyantoine.react.MusicControlNotification$NotificationService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Notification com.tanguyantoine.react.MusicControlNotification.a(android.support.v4.app.y$c, boolean)' on a null object reference
    at android.app.ActivityThread.handleCreateService(ActivityThread.java:3740)
    at android.app.ActivityThread.access$1400(ActivityThread.java:235)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:6981)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by appaaaa** [comment] 2019-03-19 05:56
You should register foreground service in manifest permission on api 28
Just add below code to android/app/src/AndroidManifest.xml
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

**Comment by tanguyantoine** [comment] 2019-03-19 07:36
@appaaaa any chance you update the readme? :-)

**Comment by The0racle** [comment] 2019-04-08 22:38
I'm still seeing this crash on our production builds. Am I missing something?

**Comment by marf** [comment] 2019-04-30 10:27
Same problem here

**Comment by tanguyantoine** [comment] 2019-05-28 07:13
did you try this ` <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` ?

**Comment by The0racle** [comment] 2019-05-28 20:53
@tanguyantoine yes.

**Comment by ouabing** [comment] 2019-05-31 05:05
Same issue here, only Android 9 devices are impacted.

**Comment by jamsch** [comment] 2019-08-10 23:57
![image](https://user-images.githubusercontent.com/12927717/62827934-1139db80-bc2f-11e9-9ae0-a563490d4b1b.png)

Issue still persists using the latest version. Affects Samsung Galaxy devices. I've already added the `FOREGROUND_SERVICE` Android permission a while back.

**Comment by marf** [comment] 2019-08-23 09:49
Are there any solutions for this problem?

**Comment by sampsonjoliver** [comment] 2019-09-24 06:47
We're also seeing this issue in our app.

**Comment by The0racle** [comment] 2019-09-26 17:36
Unfortunately this is the number of crash in our app. It literally increases crashes by 2%. If someone has a fix for this, it's much appreciated.

**Comment by The0racle** [comment] 2019-09-30 17:33
Maybe related to #276 ?

**Comment by tanguyantoine** [comment] 2019-10-01 07:05
does one of you have any Android knowledges?

**Comment by The0racle** [comment] 2019-10-07 20:54
Unfortunately I don't.

**Comment by garfiaslopez** [comment] 2019-10-21 16:19
@jamsch did you fix this?

**Comment by sampsonjoliver** [comment] 2019-10-28 06:25
Just for context, I'm seeing this issue in production across a lot more than just Samsung devices.

![image](https://user-images.githubusercontent.com/9619248/67656428-e3e80880-f9a7-11e9-88bf-4e989be7a38a.png)

**Comment by sampsonjoliver** [comment] 2019-10-28 06:27
After a little bit of digging, what I've seen so far is:

The `MusicControlModule.init` method sets the `notification` instance, and then starts the `MusicControlNotification.NotificationService`.

Then `MusicControlNotification.NotificationService.onCreate` references the `MusicControlModule.INSTANCE.notification` and calls methods on it. This wouldn't be executing if the foreground service was failing to be created due to permissions or similar.

So to my understanding, the issue is that the`INSTANCE` exists but `notification` is null. Based on lifecycle, this can _only_ happen if `MusicControlModule.stopControl` has been called, which will set `notification = null` _after_ calling `notification.hide()` which stops the service.

My best guess is that `init` is being called more than once and a second instance of `NotificationService` is attempting to run its `onCreate` after the `MusicControlModule.INSTANCE` has run `stopControl`. This could be from the application, in the react-native side, or it could be from `destroy`. Either way something is running out of order.

🤷‍♂ hope this helps give some direction to someone. I'm not sure I'll have the time to try diagnosing further to see what it is that's causing the service to run its onCreate after the notification has been stopped.

**Comment by pabloluz** [comment] 2019-11-08 20:28
Thanks for the insight, @sampsonjoliver.

From my end, I can also confirm the issue is happening in production on devices running Android 9 and 10 (mainly, but not limited to Samsung Galaxy and Moto G families).

**Comment by tanguyantoine** [comment] 2019-12-13 15:14
reproducible with `0.10.8`?

**Comment by mordonez-me** [comment] 2019-12-30 08:03
This is happening to me also:

`Process: com.mb.bl.app, PID: 4314
    java.lang.RuntimeException: Unable to create service com.tanguyantoine.react.MusicControlNotification$NotificationService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Notification com.tanguyantoine.react.MusicControlNotification.prepareNotification(androidx.core.app.NotificationCompat$Builder, boolean)' on a null object reference
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3414)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Notification com.tanguyantoine.react.MusicControlNotification.prepareNotification(androidx.core.app.NotificationCompat$Builder, boolean)' on a null object reference
        at com.tanguyantoine.react.MusicControlNotification$NotificationService.onCreate(MusicControlNotification.java:198)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3404)`

**Comment by kalpeshp0310** [comment] 2020-01-21 10:12
Some more info.
Those crashes occur after Audio focus changes or App runs out of memory.
Crash logs from our instaBug account.

```
Console
20:58:27
E/AndroidRuntime(21112): at com.tanguyantoine.react.MusicControlNotification$NotificationService.onCreate(MusicControlNotification.java:198)
Console
20:58:27
E/AndroidRuntime(21112): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Notification com.tanguyantoine.react.MusicControlNotification.prepareNotification(androidx.core.app.NotificationCompat$Builder, boolean)' on a null object reference
....
E/AndroidRuntime(21112): at android.app.ActivityThread.handleCreateService(ActivityThread.java:3817)
Console
20:58:27
E/AndroidRuntime(21112): java.lang.RuntimeException: Unable to create service com.tanguyantoine.react.MusicControlNotification$NotificationService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Notification com.tanguyantoine.react.MusicControlNotification.prepareNotification(androidx.core.app.NotificationCompat$Builder, boolean)' on a null object reference
Console
20:58:27
E/AndroidRuntime(21112): Process: ai.abridge.nativeclient.release, PID: 21112
Console
20:58:27
E/AndroidRuntime(21112): FATAL EXCEPTION: main
Console
20:58:27
D/AndroidRuntime(21112): Shutting down VM
Console
20:58:27
D/AudioManager(21112): dispatching onAudioFocusChange(-1) to android.media.AudioManager@fd19e2acom.tanguyantoine.react.MusicControlAudioFocusListener@8ed541b
```

```
Console
03:10:00
E/AndroidRuntime(31256): at com.tanguyantoine.react.MusicControlNotification$NotificationService.onCreate(MusicControlNotification.java:198)
Console
03:10:00
E/AndroidRuntime(31256): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Notification com.tanguyantoine.react.MusicControlNotification.prepareNotification(androidx.core.app.NotificationCompat$Builder, boolean)' on a null object reference
...
Console
03:10:00
E/AndroidRuntime(31256): at android.app.ActivityThread.handleCreateService(ActivityThread.java:3965)
Console
03:10:00
E/AndroidRuntime(31256): java.lang.RuntimeException: Unable to create service com.tanguyantoine.react.MusicControlNotification$NotificationService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Notification com.tanguyantoine.react.MusicControlNotification.prepareNotification(androidx.core.app.NotificationCompat$Builder, boolean)' on a null object reference
Console
03:10:00
E/AndroidRuntime(31256): Process: ai.abridge.nativeclient.release, PID: 31256
Console
03:10:00
E/AndroidRuntime(31256): FATAL EXCEPTION: main
Console
03:10:00
D/AndroidRuntime(31256): Shutting down VM
Console
03:10:00
W/MusicControlModule(31256): Control resources are being removed due to system's low memory (Level: 15)```

**Comment by ali-pedram** [comment] 2020-02-15 20:35
is anybody merging this fix ?

**Comment by FabricioCabeca** [comment] 2020-02-21 20:42
Updated yesterday to version 0.11.0, no crashes reported so far

**Comment by tanguyantoine** [comment] 2020-02-22 08:59
Should I close it?

**Comment by FabricioCabeca** [comment] 2020-02-26 16:34
> Should we close it?

It is happening much less often, but there are still some crashes in the new version, now it crashes in the onStartCommand call instead of onCreate, below is the stack trace:

> 
> java.lang.RuntimeException: 
>  
>   at android.app.ActivityThread.handleServiceArgs (ActivityThread.java:3903)
>  
>   at android.app.ActivityThread.access$1700 (ActivityThread.java:213)
>  
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1847)
>  
>   at android.os.Handler.dispatchMessage (Handler.java:106)
>  
>   at android.os.Looper.loop (Looper.java:193)
>  
>   at android.app.ActivityThread.main (ActivityThread.java:6923)
>  
>   at java.lang.reflect.Method.invoke (Native Method)
>  
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
>  
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:870)
> Caused by: java.lang.NullPointerException: 
>  
>   at com.tanguyantoine.react.MusicControlNotification$NotificationService.onStartCommand (MusicControlNotification.java:194)
>  
>   at android.app.ActivityThread.handleServiceArgs (ActivityThread.java:3884)

**Comment by pabloluz** [comment] 2020-02-26 20:15
@tanguyantoine I'm experiencing the same as @FabricioCabeca

**Comment by weareyou-laurens** [comment] 2020-02-27 10:50
We are also experiencing this issue at production on a daily basis.
Devices where the crashes appear most often;

- Galaxy Tab A
- Galaxy S9
- HUAWEI Y6 2019

We use version 0.10.8 of react-native-music-control, and we have about 16 users affected by crashes every month. We do have the FOREGROUND_SERVICE permission configured.

Do you think upgrading to 0.11.0 would reduce the amount of crashes experienced?
Thanks for any help!

**Comment by pabloluz** [comment] 2020-02-27 19:42
@weareyou-laurens `0.11.0` doesn't fix the issue entirely. See @FabricioCabeca 's comment above.

**Closed** 2020-03-09 08:20 UTC
Labels: Android, bug

**Comment by noway** [comment] 2021-04-07 02:37
This should be reopened. There's no fix for the crash @FabricioCabeca is experiencing yet.

**Comment by noway** [comment] 2021-04-07 02:47
@FabricioCabeca have you had a chance to try out the #381 fix? I wonder if that fixes your issue since it touches onStartCommand too.

**Comment by leogiroux** [comment] 2021-04-19 08:27
I can confirm that I have a lot of crashes from this lib 
`Attempt to invoke virtual method 'android.app.Notification com.tanguyantoine.react.MusicControlNotification.prepareNotification(androidx.core.app.NotificationCompat$Builder, boolean)' on a null object reference `

Do you guys have an lib alternative or a solution for this ? I will try  #381 too.

**Comment by nahuelb** [comment] 2021-04-27 19:02
I tried #381 and I am still having this issue.

**Comment by krunalbad** [comment] 2021-04-28 07:50
@nahuelb Do you have any other media pkg installed in ur application? Cuz Different channels might create conflicts in Android devices.
