### ISSUE TITLE
[Android] Always show controls MC

### ISSUE THREAD

**Issue by mrsydster** [tanguyantoine/react-native-music-control#103] opened 2017-10-29 16:02 UTC
How can I make sure that music control will always show the controls on the notifications?

I want to have the same as the app above on the screenshot. Not having to expand the notification.
![screenshot_20171029-165916](https://user-images.githubusercontent.com/21159289/32145538-c9958de8-bcca-11e7-97c0-437059c05b17.png)

**Comment by Guichaguri** [comment] 2017-10-29 18:36
Duplicate of #67

**Closed by Guichaguri** 2017-10-29 18:36 UTC
Labels: Android, duplicate
