### ISSUE TITLE
iOS Real device not working

### ISSUE THREAD

**Issue by nhoclove9x** [tanguyantoine/react-native-music-control#53] opened 2017-03-29 12:36 UTC
# Description

1. Sample code (provide repo url or sample code)
 i using sample like readme file. great works on simulator but not working on iPhone 7 iOS 10.
help me.

sorry bad english!

2. Platform ?
   -  iOS
   
   
3. Device
  - Real device

**Comment by tanguyantoine** [comment] 2017-04-03 18:06
Could you share your repo ?

**Comment by menan** [comment] 2017-04-11 02:23
I am having this issue as well.

**Comment by tanguyantoine** [comment] 2017-04-15 11:13
Would you mind explaining precisely what is nor working ?

**Comment by menan** [comment] 2017-04-17 03:10
It just won't show anything I set, in the Control Centre or Lock Screen on my device. It works fine in Android device and iOS simulators. Only in devices I see nothing.

**Comment by zdol** [comment] 2017-05-17 09:03
Any news on this? Any ideas?

**Comment by tanguyantoine** [comment] 2017-05-17 20:21
@zdol do you have the same issue ?

**Comment by zdol** [comment] 2017-05-17 21:00
Yes, on iOS simulator it mostly works, but on real device nothing happens.

**Comment by tanguyantoine** [comment] 2017-05-18 11:45
would you mind sharing your app ?

**Comment by zdol** [comment] 2017-05-18 12:27
Sorry, I cannot share full code right now. For all it matters, I essentially just tried the 'Michael Jackson' example code found here. The app's functionality is like a remote control.

I found what the problem is, though. If there is no sound playback initiated (like in your demo app using react-native-sound) the controls will not change. I put a 10 sec. silent track to play. although this might not be an optimal solution, eventually.

Strange that it works in the simulator though and not the device itself. I tried many, many things, before resorting to the dummy audio playback solution. If you know any other workarounds for this, please let me know.

**Comment by tanguyantoine** [comment] 2017-05-18 17:37
any chance to made a PR on the demo app ?

**Comment by zdol** [comment] 2017-05-19 09:47
I made a pull request on the demo app.

I added a couple of buttons to showcase this bug
If you press "PLAY NO AUDIO" or "UPDATE INFO":
- on the iOS simulator, control center info will change
- on iOS device, nothing happens

If you press "PLAY SONG" (nothing really changed there) playback starts and afterwards the other two buttons function properly in both cases (simulator/device)

I'm on iOS 10.3.2.

**Comment by tanguyantoine** [comment] 2017-05-20 13:47
could you re-test with the new version published 0.4.4 ?

**Comment by menan** [comment] 2017-05-22 14:45
Tried it with `0.4.4` still not working.

**Comment by zoranmarjanovic** [comment] 2017-05-30 14:18
+1, any updates on this one

**Comment by tanguyantoine** [comment] 2017-05-30 18:40
which RN version do you have ?

**Comment by bestseob93** [comment] 2017-05-31 04:41
it works on my device (iphone 6s, ios 10.3)

**Comment by zoranmarjanovic** [comment] 2017-05-31 07:07
@tanguyantoine RN version: 0.42.3 
It is interesting, it works in android and simulator but it doesn't work on iphone SE and iphone 5s

**Comment by zdol** [comment] 2017-05-31 13:16
Developing with the iPhone SE as well here. Still got the issues I described above. Maybe it's an iOS bug. I read elsewhere that the simulator is not to be trusted always, especially when it has to do with control center.

To people with larger phones, does the module work without any actual audio playing? That seems to be the culprit.

**Comment by gaodeng** [comment] 2017-06-04 17:16
RN version:0.42.3.When run in  the simulator it is working as expected, but Iphone SE real Device not working, not show any thing in control center.

**Comment by QQizi** [comment] 2017-06-18 14:02
Same problem here, Simulator is ok, with or without any sound playing.
Iphone 6, IOS 10.3.2, nothing in the control center

**Comment by tanguyantoine** [comment] 2017-06-19 01:24
Yes, sorry I had no time to handle this issue. I will try to give it a try during the week, hopefully

**Comment by tanguyantoine** [comment] 2017-06-19 01:27
@QQizi do you have a public repo where I can see what you did ?

**Comment by tanguyantoine** [comment] 2017-06-23 01:17
@QQizi  ?

**Comment by natashache** [comment] 2017-07-25 15:49
@tanguyantoine any update on this? I'm having the same issue. It's not showing on real iphone.

**Comment by tanguyantoine** [comment] 2017-07-25 16:01
Can you post your device configuration?

**Comment by QQizi** [comment] 2017-07-25 16:03
@tanguyantoine & @natashache sorry for the late answer.
I'v managed to fixe it, it was a mistake from my side for sure since it's working now.

@tanguyantoine does 
`<key>UIBackgroundModes</key>
    <array>
      <string>audio</string>
    </array>`
ring any bell to you ? I think that's what i needed to add to my plist.

**Comment by natashache** [comment] 2017-07-25 16:19
@QQizi How did you fix it? By adding that line of code to your plist?

**Comment by tanguyantoine** [comment] 2017-07-25 16:30
@QQizi any chance to get a PR adding this step to the documentation if it is not present ?

:+1:

**Comment by QQizi** [comment] 2017-07-25 16:38
@natashache Try it and let me know if that fixed your problem.

**Comment by QQizi** [comment] 2017-07-25 16:50
@natashache BTW, did you had those lines :
`MusicControl.enableControl('play', true)
MusicControl.enableControl('pause', true)
MusicControl.enableControl('stop', true)`

Before using : 

`MusicControl.setNowPlaying({})`

It is not clearly explained in the documentation that you need to enable the controls before using the setNowPlaying method

**Comment by natashache** [comment] 2017-07-25 20:52
@QQizi I have

**Comment by tanguyantoine** [comment] 2017-07-26 15:57
@natashache can you test by enabling background mode setting in XCode too ?
<img width="1146" alt="screen shot 2017-07-26 at 17 55 45" src="https://user-images.githubusercontent.com/263097/28630866-beb84094-722b-11e7-8ed2-b495c9f37956.png">

If it works please respond here in order to close the issue. I will update the README accordingly

**Comment by natashache** [comment] 2017-07-27 03:05
@tanguyantoine will test it this weekend. Thanks!

**Comment by tanguyantoine** [comment] 2017-07-29 22:43
I updated the README : https://github.com/tanguyantoine/react-native-music-control/pull/74 

when you confirm it fixes your problem @natashache I close this issue

**Comment by natashache** [comment] 2017-07-31 03:05
@tanguyantoine I tried again. Still didn't work. No lock screen control showing up on real device. I tried 1) adding `<key>UIBackgroundModes</key> <array> <string>audio</string> </array>` to info.plist; 2) enabled background mode in XCode; 3) added `MusicControl.enableControl('play', true) MusicControl.enableControl('pause', true) MusicControl.enableControl('stop', true)` before `setNowPlaying`.

**Comment by menan** [comment] 2017-08-14 21:29
It still doesn't work @tanguyantoine

**Comment by tanguyantoine** [comment] 2017-08-14 22:55
can you , both of you, send us the link to your repo and step reproduce it ?
do you hame the same issue with the demo app https://github.com/tanguyantoine/react-native-music-control-demo ?

**Comment by gvenk** [comment] 2017-09-01 14:27
Looks like I ran into the same problem :-( iOS simulator is working perfect, but on a real device (iPhone 6/iOS10) it's not working. 

Demo app is also not working (can't even hear the audio play, have to look why)

**Comment by gvenk** [comment] 2017-09-01 15:23
Looks like I found my problem. I'm using react-native-sound and was using `Sound.setCategory('Playback', true)`, so mixWithOthers = true. If I set this to false, the MusicControl shows the correct info, even on a Real device :-)

**Comment by tanguyantoine** [comment] 2017-09-01 16:49
any chance you detail this in the readme ?

**Comment by gvenk** [comment] 2017-09-01 22:26
@tanguyantoine I'll try to add some info to the readme and submit a PR

**Comment by tanguyantoine** [comment] 2017-09-02 00:00
@nhoclove9x @menan @natashache @zoranmarjanovic @zdol could this react-native-sound's trick solve the issue ?

**Comment by tanguyantoine** [comment] 2017-09-17 03:37
no response, no error anymore 😁

**Closed by tanguyantoine** 2017-09-17 03:37 UTC
Labels: iOS

**Comment by jandog8990** [comment] 2020-02-23 06:38
Hello, has anyone figured out this issue? I've tried everything mentioned above, from setting the Info.plist to enabling the controls prior to setNowPlaying, and also background processes in XCode. I'm using an iPhone 11 simulator as I do not have an iphone. I'm coding a react-native app and it's not working with the react-native-video module. Thank you and Here's some code:

```
			// Enable the Basic Controls for the controller
			this.enableMusicControl();	
			MusicControl.setNowPlaying({
				title: audio.TITLE || "",
				artwork: audio.PHOTO_LOC || "",
				artist: audio.AUTHOR || "",
				album: audio.TITLE || "",
				genre: audio.GENRE || "",
				duration: audio.DURATION || 0,
				rating: true
			});

			const elapsedTime = this.props.playerControlContainer.state.currentPosition;
			MusicControl.updatePlayback({
				state: MusicControl.STATE_PLAYING,
				elapsedTime: elapsedTime,
				maxVolume: 10,
				rating: MusicControl.RATING_HEART 
			});
```
