### ISSUE TITLE
Working on iOS 12 ?

### ISSUE THREAD

**Issue by RocKhalil** [tanguyantoine/react-native-music-control#242] opened 2019-02-26 16:11 UTC
# Description

1. Sample code (provide repo url or sample code)
```
      Sound.setCategory('Playback', false);
      MusicControl.enableBackgroundMode(true);

      var whoosh = new Sound('song.mp3', Sound.MAIN_BUNDLE, (error) => {
        if (error) {
          console.log('failed to load the sound', error);
          return;
        }
        // loaded successfully
        console.log('duration in seconds: ' + whoosh.getDuration() + 'number of channels: ' + whoosh.getNumberOfChannels());

        // Play the sound with an onEnd callback
        whoosh.play()

        MusicControl.setNowPlaying({
          title: 'Billie Jean',
          artwork: 'https://i.imgur.com/e1cpwdo.png', // URL or RN's image require()
          artist: 'Michael Jackson',
          album: 'Thriller',
          genre: 'Post-disco, Rhythm and Blues, Funk, Dance-pop',
          elapsedTime: 10,
          duration: whoosh.getDuration(), // (Seconds)
        })

        MusicControl.enableControl('pause', true)

        alert(1)
      })
```

2. Platform ?

   - [X] iOS
   - [ ] Android
   
   
3. Device
  - [X] Simulator
  - [X] Real device

I'm trying to test it on iOS 12; I'm getting the `alert` and the music is playing, however, the controls aren't showing on the lock screen.

I've cloned the demo project, and it's not working there too.

Is there any issue on iOS 12 ?

[P.S]: Tried it on iOS 10.3.3 and it's working fine.

**Comment by tanguyantoine** [comment] 2019-02-27 07:49
duplicate of #239 ?

**Comment by RocKhalil** [comment] 2019-02-27 09:10
@tanguyantoine maybe.. not sure what the guy there did.
Any idea how that can be solved ? 

I think there's an issue in the `MPRemoteCommandCenter` on iOS 12 cause it's only reading data when we open/use an `AVPlayerViewController`.

If you try playing music with an `AVPlayer` without integrating it in the  `AVPlayerViewController` and presenting it on the app, the controls are not showing (this is a test I did in Objective C and Swift).

So I'm not sure if it's a library issue here or an OS issue, but it's good to mention it on this thread to see if someone has an answer.

**Comment by GH974** [comment] 2019-02-28 04:20
Hi, it work for me, except this command not work for me in IOS.
`MusicControl.enableControl('stop', true);`

Thanks.

**Closed** 2019-04-26 14:42 UTC
